/*
 * This code was generated automatically. Do NOT edit this file, changes will be lost.
 */
package logic.to;

import java.io.Serializable;

public abstract class AbstractEntityTO implements Serializable {

    private static final long serialVersionUID = -4670166606829520754L;
    private Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
